const url = {
  TRAINER_LOGIN: '/login',
  TRAINER_REGISTER: '/register',
  GET_TRAINERS: '/alltrainers',
  TRAINER_UPDATE: '/update',
  TRAINER_DELETE: '/delete/',
  TRAINER_STATUS:'/status/',
TRAINER_ADDPOST:'/addpost',
TRAINER_POSTS:"/posts",
TRAINER_POST_DELETE:"/post/delete/",
ALL_POSTS:"/allposts",
ADD_PLAN:"/addplan",
GET_TRAINERS_PLANS:"/gettrainerplan",
GET_SINGLE_PLAN:"/singleplan/",
DELETE_PLAN:"/deleteplan/",
GET_TRAINER_CLIENTS:"/getclients"

}
export const  {
  GET_TRAINERS,
  TRAINER_LOGIN,
  TRAINER_REGISTER,
  TRAINER_DELETE,
  TRAINER_UPDATE,
  TRAINER_STATUS,
  TRAINER_ADDPOST,
  TRAINER_POSTS,
  TRAINER_POST_DELETE,
  ALL_POSTS,
  ADD_PLAN,
  GET_TRAINERS_PLANS,
  GET_SINGLE_PLAN,
  DELETE_PLAN,
  GET_TRAINER_CLIENTS
} =url
