const urls = {
  USER_REGISTER: '/register',
  USER_LOGIN: '/login',
  GET_USER: '/user',
  USER_STATUS: '/status/',
  USER_UPDATE: '/update',
  USER_ADDPOST: '/addpost',
  USER_POSTS: '/posts',
  USER_DELETE_POST: '/posts/delete',
  USER_ALL_POSTS: '/allposts',
  SINGLE_TRAINER: '/singletrainer/',
  GET_ALL_PLANS: '/allplans',
  GET_SINGLE_PLAN: '/singleplan/',
  GET_SINGLE_TRAINER_PLANS:"/trainerplans/",
  USER_OWN_PLAN:"/userownplan",
  GOOGLE_LOGIN:"/googlelogin",
  LIKE_POST:"/likepost/",
  GET_CONVERSATIONS:"/conversations/",
  GET_SINGLE_USER:'/singleuser/',
  GET_MESSAGES:"/messages/",
  ADD_MESSAGES:"/messages",
}


export const {
  GET_USER,
  USER_LOGIN,
  USER_REGISTER,
  USER_STATUS,
  USER_UPDATE,
  USER_ADDPOST,
  USER_POSTS,
  USER_DELETE_POST,
  USER_ALL_POSTS,
  SINGLE_TRAINER,
  GET_ALL_PLANS,
  GET_SINGLE_PLAN,
  GET_SINGLE_TRAINER_PLANS,
  USER_OWN_PLAN,
  GOOGLE_LOGIN,
  LIKE_POST,
  GET_CONVERSATIONS,
  GET_SINGLE_USER,
  GET_MESSAGES,
  ADD_MESSAGES
} = urls
